FROM golang:1.19.0-alpine3.16

COPY . $GOPATH/src/github.com/microservices-demo/payment
WORKDIR $GOPATH/src/github.com/microservices-demo/payment

RUN apk update && apk add --no-cache gcc libc-dev

RUN go test
RUN cd $GOPATH/src/github.com/microservices-demo/payment/cmd/paymentsvc && go install

FROM alpine:3.16

WORKDIR /
EXPOSE 80
COPY --from=0 /go/bin/paymentsvc /app

ARG BUILD_DATE
ARG BUILD_VERSION
ARG COMMIT

LABEL org.label-schema.vendor="Weaveworks" \
  org.label-schema.build-date="${BUILD_DATE}" \
  org.label-schema.version="${BUILD_VERSION}" \
  org.label-schema.name="Socks Shop: Payment" \
  org.label-schema.description="REST API for Payment service" \
  org.label-schema.url="https://github.com/cams7-tests/sockshop-payment" \
  org.label-schema.vcs-url="github.com/cams7-tests/sockshop-payment.git" \
  org.label-schema.vcs-ref="${COMMIT}" \
  org.label-schema.schema-version="1.0.1"

CMD ["/app", "-port=80"]